import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  Ban,
  BarChart3,
  Bell,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDashed,
  ClipboardList,
  Clock,
  Columns3,
  Copy,
  Download,
  ExternalLink,
  Factory,
  FileCheck2,
  FileText,
  Filter,
  FolderOpen,
  Home,
  Inbox,
  Info,
  Leaf,
  LogOut,
  type LucideIcon,
  Map,
  MapPin,
  Menu,
  Monitor,
  Minus,
  MoreHorizontal,
  Package,
  Smartphone,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Shield,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  Users,
  Wallet,
  X,
  XCircle,
} from 'lucide-react';

/**
 * The icon set: the only icons the app uses. Features import icons from `@/ui`, never from lucide-react, so the
 * set stays small and consistent. Add an icon here when a screen needs one.
 */
export const icons = {
  alert: AlertTriangle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  ban: Ban,
  bell: Bell,
  calendar: Calendar,
  chart: BarChart3,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  clipboard: ClipboardList,
  clock: Clock,
  close: X,
  columns: Columns3,
  copy: Copy,
  download: Download,
  draft: CircleDashed,
  edit: Pencil,
  error: XCircle,
  external: ExternalLink,
  factory: Factory,
  file: FileText,
  filter: Filter,
  folderOpen: FolderOpen,
  home: Home,
  inbox: Inbox,
  info: Info,
  leaf: Leaf,
  logout: LogOut,
  map: Map,
  mapPin: MapPin,
  menu: Menu,
  monitor: Monitor,
  minus: Minus,
  more: MoreHorizontal,
  package: Package,
  phone: Smartphone,
  panelClose: PanelLeftClose,
  panelOpen: PanelLeftOpen,
  plus: Plus,
  posted: FileCheck2,
  refresh: RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  sortable: ArrowUpDown,
  trash: Trash2,
  trendDown: TrendingDown,
  trendUp: TrendingUp,
  upload: Upload,
  user: User,
  users: Users,
  wallet: Wallet,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
