import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Ban,
  Bell,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  CircleDashed,
  Download,
  ExternalLink,
  FileCheck2,
  FileText,
  Filter,
  Info,
  Leaf,
  LogOut,
  type LucideIcon,
  Menu,
  MoreHorizontal,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Trash2,
  Upload,
  User,
  X,
  XCircle,
} from 'lucide-react';

/**
 * The icon set: the only icons the app uses. Features import icons from `@/ui`, never from lucide-react, so the
 * set stays small and consistent. Add an icon here when a screen needs one.
 */
export const icons = {
  alert: AlertTriangle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  ban: Ban,
  bell: Bell,
  calendar: Calendar,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  clock: Clock,
  close: X,
  draft: CircleDashed,
  download: Download,
  edit: Pencil,
  file: FileText,
  error: XCircle,
  external: ExternalLink,
  filter: Filter,
  info: Info,
  leaf: Leaf,
  logout: LogOut,
  menu: Menu,
  more: MoreHorizontal,
  plus: Plus,
  posted: FileCheck2,
  refresh: RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  trash: Trash2,
  upload: Upload,
  user: User,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
