import { type TFunction } from 'i18next';

import { type UiText } from '@/ui';

/**
 * The component library's words in the active language, from the i18n `ui` namespace. ui/ stays free of the
 * i18n library; the app hands it this dictionary through UiProvider and rebuilds it when the language changes.
 */
export function buildUiText(t: TFunction<'ui'>, language: string): UiText {
  const bn = language === 'bn';
  return {
    numberLocale: bn ? 'bn-BD' : 'en-US',
    dateLocale: bn ? 'bn-BD' : 'en-GB',
    close: t('close'),
    dismiss: t('dismiss'),
    cancel: t('cancel'),
    tryAgain: t('tryAgain'),
    actionFailed: t('actionFailed'),
    loading: t('loading'),
    updating: t('updating'),
    notSet: t('notSet'),
    unnamedPerson: t('unnamedPerson'),
    choose: t('choose'),
    errorTitle: t('errorTitle'),
    errorMessage: t('errorMessage'),
    reference: t('reference'),
    copyReference: t('copyReference'),
    referenceCopied: t('referenceCopied'),
    notifications: t('notifications'),
    closeNotification: t('closeNotification'),
    typeToSearch: t('typeToSearch'),
    noMatches: t('noMatches'),
    searching: t('searching'),
    loadingMore: t('loadingMore'),
    showResults: t('showResults'),
    columns: t('columns'),
    sortBy: t('sortBy'),
    sortOption: (column, descending) => t(descending ? 'sortDescending' : 'sortAscending', { column }),
    bulkActions: t('bulkActions'),
    selectedCount: (count) => t('selectedCount', { count }),
    clearSelection: t('clearSelection'),
    selectAllOnPage: t('selectAllOnPage'),
    selectRow: (row) => t('selectRow', { row }),
    allOnPageSelected: (count) => t('allOnPageSelected', { count }),
    selectionCleared: t('selectionCleared'),
    loadMore: t('loadMore'),
    showing: (count, isAll) => t(isAll ? 'showingAll' : 'showing', { count }),
    noRows: (label) => t('noRows', { label }),
    loadFailed: (label) => t('loadFailed', { label }),
    rowsPerPage: t('rowsPerPage'),
    pagination: t('pagination'),
    previousPage: t('previousPage'),
    nextPage: t('nextPage'),
    pageNumber: (page) => t('pageNumber', { page }),
    pageOf: (page, pages) => t('pageOf', { page, pages }),
    range: (first, last, total, items) => t('range', { first, last, total, items }),
    noItems: (items) => t('noItems', { items }),
    rows: t('rows'),
    mainNavigation: t('mainNavigation'),
    navigation: t('navigation'),
    breadcrumbs: t('breadcrumbs'),
    openNavigation: t('openNavigation'),
    closeNavigation: t('closeNavigation'),
    expandNavigation: t('expandNavigation'),
    collapseNavigation: t('collapseNavigation'),
    skipToMain: t('skipToMain'),
    needAttention: (count) => t('needAttention', { count }),
    account: (name) => t('account', { name }),
    step: (index, total, state) =>
      t(state === 'complete' ? 'stepComplete' : state === 'current' ? 'stepCurrent' : 'stepUpcoming', {
        index,
        total,
      }),
    remove: (label) => t('remove', { label }),
    documentState: {
      draft: t('documentState.draft'),
      submitted: t('documentState.submitted'),
      approved: t('documentState.approved'),
      posted: t('documentState.posted'),
      rejected: t('documentState.rejected'),
      cancelled: t('documentState.cancelled'),
    },
    calendar: (label) => t('calendar', { label }),
    datePresets: {
      today: t('datePresets.today'),
      yesterday: t('datePresets.yesterday'),
      'last-7-days': t('datePresets.last-7-days'),
      'this-month': t('datePresets.this-month'),
      'last-month': t('datePresets.last-month'),
    },
    characterCount: (length, max) => t('characterCount', { length, max }),
    multiSelected: (count) => t('multiSelected', { count }),
    currencyName: t('currencyName'),
    kilograms: t('kilograms'),
    inUnit: (unit) => t('inUnit', { unit }),
    dropFilesHere: t('dropFilesHere'),
    chooseFile: t('chooseFile'),
    chooseFiles: t('chooseFiles'),
    attachedFiles: t('attachedFiles'),
    uploaded: t('uploaded'),
    uploading: (file) => t('uploading', { file }),
    fileRules: (types, maxSize, multiple) => t(multiple ? 'fileRulesEach' : 'fileRules', { types, maxSize }),
    fileTypeRefused: (file) => t('fileTypeRefused', { file }),
    fileTooLarge: (file, maxSize, size) => t('fileTooLarge', { file, maxSize, size }),
    filesAdded: (count) => t('filesAdded', { count }),
    fileRemoved: (file) => t('fileRemoved', { file }),
  };
}
